# Generated by Django 3.0.3 on 2020-03-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlhAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlhuser',
            name='isOrganizer',
            field=models.BooleanField(default=False),
        ),
    ]
