# Generated by Django 3.0.3 on 2020-03-29 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlhAuth', '0002_mlhuser_isorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlhuser',
            name='muteInstances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlhuser',
            name='muteUntilTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlhuser',
            name='permanentMute',
            field=models.BooleanField(default=False),
        ),
    ]
