# Generated by Django 3.0.3 on 2020-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlhAuth', '0003_auto_20200328_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlhuser',
            name='token',
            field=models.CharField(default='', max_length=10),
        ),
    ]
