# Generated by Django 3.0.3 on 2020-04-26 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlhAuth', '0004_mlhuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlhuser',
            name='muteUntilTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
