# Generated by Django 3.0.3 on 2020-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(default='', max_length=1024)),
                ('author', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
