# Generated by Django 3.0.3 on 2020-03-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(default='general', max_length=128)),
                ('organizerOnly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(default='', max_length=2048)),
                ('messageTimestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_id_for_message_author', to=settings.AUTH_USER_MODEL)),
                ('channelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_id_for_message', to='chat.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionStatus', models.IntegerField(default=0)),
                ('channelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_id_for_permission', to='chat.Channel')),
                ('participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_id_for_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
