# Generated by Django 3.0.3 on 2020-03-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpermissions',
            name='newUserPermissionStatus',
            field=models.IntegerField(default=2),
        ),
    ]
