# Generated by Django 3.0.3 on 2020-03-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_channelpermissions_newuserpermissionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpermissions',
            name='newUserPermissionStatus',
        ),
        migrations.AddField(
            model_name='channel',
            name='newUserPermissionStatus',
            field=models.IntegerField(default=2),
        ),
    ]
