# Generated by Django 3.0.3 on 2020-04-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200330_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpermissions',
            name='lastReadMessage',
            field=models.IntegerField(default=1),
        ),
    ]
